# Generated by Django 5.0.3 on 2025-10-13 05:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_hierarchy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_hierarchy.diocese', verbose_name='Епархия'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('role', models.CharField(choices=[('admin', 'Администратор епархии'), ('chief', 'Главный миссионер'), ('missionary', 'Миссионер')], verbose_name='Роль')),
                ('code', models.CharField(db_index=True, unique=True, verbose_name='Код')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 10, 27, 5, 57, 4, 153874, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения приглашения')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_hierarchy.diocese', verbose_name='Епархия')),
            ],
            options={
                'verbose_name': 'Приглашения',
            },
        ),
    ]
