# Generated by Django 5.0.3 on 2025-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, null=True, verbose_name='Код активации'),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время до конца активации'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, null=True, verbose_name='Код активации'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время до конца активации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
