# Generated by Django 5.0.3 on 2025-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_activation_code_user_activation_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_permission',
            field=models.BooleanField(default=False, verbose_name='Доступ к задачам'),
        ),
    ]
