# Generated by Django 5.0.3 on 2025-10-13 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_diocese_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 11, 59, 53, 850826, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения приглашения'),
        ),
    ]
