# Generated by Django 5.0.3 on 2025-10-13 12:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invite_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='Приглашение от'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 12, 43, 5, 106102, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения приглашения'),
        ),
    ]
