# Generated by Django 5.0.3 on 2025-10-13 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invite_invite_by_alter_invite_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
        migrations.AlterField(
            model_name='invite',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 13, 28, 40, 435376, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения приглашения'),
        ),
    ]
