# Generated by Django 5.0.3 on 2025-10-14 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_invite_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 11, 25, 43, 468237, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения приглашения'),
        ),
    ]
