# Generated by Django 5.0.3 on 2025-10-15 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_invite_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, null=True, verbose_name='Город проживания'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronumic',
            field=models.CharField(blank=True, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 5, 51, 32, 306194, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения приглашения'),
        ),
    ]
