# Generated by Django 5.0.3 on 2025-10-17 06:50

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_city_user_date_of_birth_user_image_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='deadline',
            field=models.DateTimeField(default=apps.users.models.get_deadline, verbose_name='Дата истечения приглашения'),
        ),
    ]
