# Generated by Django 5.0.3 on 2025-10-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_invite_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patronumic',
            new_name='patronymic',
        ),
    ]
