# Generated by Django 5.0.3 on 2025-10-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_hierarchy', '0003_remove_diocese_chief_missionary_diocese_chief'),
        ('users', '0012_rename_patronumic_user_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('accepted', 'Переведен'), ('closed', 'Закрыт')], default='created', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='local_hierarchy.diocese', verbose_name='Епархия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='local_hierarchy.diocese', verbose_name='Епархия'),
        ),
    ]
