# Generated by Django 5.0.3 on 2025-04-11 12:47

import django.db.models.deletion
import streamfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('stream', streamfield.fields.StreamField(blank=True, default=list, verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлереи',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/content/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сео блок',
                'verbose_name_plural': 'Сео блоки',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='content/gallery/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.galleryblock', verbose_name='Галлерея')),
            ],
            options={
                'verbose_name': 'Элемент галлереи',
                'verbose_name_plural': 'Элементы галлереи',
            },
        ),
    ]
