# Generated by Django 5.0.3 on 2025-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoblock',
            name='position',
            field=models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='right', verbose_name='Положение изображения'),
        ),
    ]
