# Generated by Django 5.0.3 on 2025-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seoblock_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='in_line',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='3', max_length=1, verbose_name='Элементов в линии'),
        ),
    ]
