# Generated by Django 5.0.3 on 2025-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_content'),
        ('content', '0003_galleryitem_in_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Заголовок')),
                ('products', models.ManyToManyField(to='catalog.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Блок продуктов',
                'verbose_name_plural': 'Блоки продуктов',
            },
        ),
    ]
