# Generated by Django 5.0.3 on 2025-04-25 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_fileblock_fileitem'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Заголовок')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Ограничение')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.heading')),
            ],
            options={
                'verbose_name': 'Блок рубрики',
                'verbose_name_plural': 'Блоки рубрики',
            },
        ),
    ]
