# Generated by Django 5.0.3 on 2025-06-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_headingblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='in_line',
        ),
        migrations.AddField(
            model_name='galleryblock',
            name='in_line',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='3', max_length=1, verbose_name='Элементов в линии'),
        ),
    ]
