# Generated by Django 5.0.3 on 2025-07-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_galleryitem_in_line_galleryblock_in_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadingBlock',
        ),
    ]
