# Generated by Django 5.0.3 on 2025-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApishipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadata_token', models.CharField(null=True, verbose_name='Dadata token')),
                ('dadata_secret', models.CharField(null=True, verbose_name='Dadata secret')),
                ('apiship_token', models.CharField(null=True, verbose_name='Apiship token')),
            ],
            options={
                'verbose_name': 'Настройки apiship',
                'verbose_name_plural': 'Настройки apiship',
            },
        ),
    ]
