# Generated by Django 5.0.3 on 2025-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apishipsettings',
            name='from_city',
            field=models.CharField(blank=True, null=True, verbose_name='Город отправления'),
        ),
        migrations.AddField(
            model_name='apishipsettings',
            name='from_city_guid',
            field=models.CharField(null=True, verbose_name='GUID города'),
        ),
    ]
