# Generated by Django 5.0.3 on 2025-05-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ballons',
        ),
    ]
