# Generated by Django 5.0.3 on 2025-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Почта администратора',
                'verbose_name_plural': 'Почты администраторов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('extra', models.TextField(null=True, verbose_name='Дополнительно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
