# Generated by Django 5.0.3 on 2025-04-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Имя атрибута',
                'verbose_name_plural': 'Имена атрибутов',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибута',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.PositiveIntegerField(default=0, verbose_name='Посещения'),
        ),
        migrations.CreateModel(
            name='AttributeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='catalog.attributename', verbose_name='Имя атрибута')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product', verbose_name='Продукт')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='catalog.attributevalue', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Атрибут продукта',
                'verbose_name_plural': 'Атрибуты продуктов',
            },
        ),
    ]
