# Generated by Django 5.0.3 on 2025-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attributename_attributevalue_product_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, null=True, verbose_name='Артикул'),
        ),
    ]
