# Generated by Django 5.0.3 on 2025-04-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_code'),
        ('content', '0003_galleryitem_in_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content', verbose_name='Контент'),
        ),
    ]
