# Generated by Django 5.0.3 on 2025-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_hit_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Длина'),
        ),
    ]
