# Generated by Django 5.0.3 on 2025-10-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diocese',
            options={'verbose_name': 'Епархия', 'verbose_name_plural': 'Епархии'},
        ),
    ]
