# Generated by Django 5.0.3 on 2025-10-24 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_hierarchy', '0002_alter_diocese_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diocese',
            name='chief_missionary',
        ),
        migrations.AddField(
            model_name='diocese',
            name='chief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_in', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за ЕМО'),
        ),
    ]
