# Generated by Django 5.0.3 on 2025-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=255, verbose_name='Функция')),
                ('args', models.TextField(blank=True, null=True, verbose_name='Позиционные аргументы')),
                ('kwargs', models.TextField(blank=True, null=True, verbose_name='Именованные аргументы')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('status', models.CharField(blank=True, choices=[('success', 'Успех'), ('error', 'Ошибка')], max_length=50, null=True, verbose_name='Статус')),
                ('pid', models.CharField(max_length=200)),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('watched', models.BooleanField(default=False, verbose_name='Просмотрено')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='DjangoJobExecutionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Рассписание (Выполнения)',
                'verbose_name_plural': 'Рассписание (Выполнения)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_apscheduler.djangojobexecution',),
        ),
        migrations.CreateModel(
            name='DjangoJobProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Рассписание',
                'verbose_name_plural': 'Рассписание',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_apscheduler.djangojob',),
        ),
    ]
