# Generated by Django 5.0.3 on 2025-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='watched',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
