# Generated by Django 5.0.3 on 2025-10-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookwishlist',
            options={'verbose_name': 'Список понравившихся книг', 'verbose_name_plural': 'Списоки понравившихся книг'},
        ),
    ]
