# Generated by Django 5.0.3 on 2025-04-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Получается у BotFather в телеграм пишем команду /newbot и после его имя оканчивающееся на _bot, в поле вставляем полученный токен', verbose_name='Токен')),
                ('chat_ids', models.TextField(help_text='Получается у userinfobot, пишем /start и забираем от туда поле Id', verbose_name='Ид чатов')),
            ],
            options={
                'verbose_name': 'Настройки телеграм бота',
                'verbose_name_plural': 'Настройки телеграм бота',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('slug', models.CharField(blank=True, default='', unique=True, verbose_name='Слаг')),
                ('name', models.CharField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
        migrations.CreateModel(
            name='RootSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВКонтакте')),
                ('tg_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Телеграм')),
                ('wa_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на WhatsApp')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('company_name', models.CharField(verbose_name='Имя компании')),
                ('scripts', models.TextField(blank=True, null=True, verbose_name='Скрипты')),
                ('robots', models.TextField(default='User-agent: *\nDisallow: /')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='IndexSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, default='', max_length=300, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Настройки главной',
                'verbose_name_plural': 'Настройки главной',
            },
        ),
    ]
