# Generated by Django 5.0.3 on 2025-10-10 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('slug', models.CharField(blank=True, default='', unique=True, verbose_name='Слаг')),
                ('name', models.CharField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
        migrations.CreateModel(
            name='RootSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Почта')),
                ('company_name', models.CharField(verbose_name='Имя компании')),
                ('logo', models.ImageField(null=True, upload_to='images/settings/', verbose_name='Логотип')),
                ('favicon', models.ImageField(null=True, upload_to='images/settings/', verbose_name='Фавикон')),
                ('scripts', models.TextField(blank=True, null=True, verbose_name='Скрипты')),
                ('robots', models.TextField(default='User-agent: *\nDisallow: /')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
