# Generated by Django 5.0.3 on 2025-10-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0002_diary_description_alter_diary_advantages'),
        ('local_hierarchy', '0002_alter_diocese_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('start_period', models.CharField(help_text='Пример 20.08', verbose_name='Начало')),
                ('end_period', models.CharField(help_text='Пример 20.08', verbose_name='Конец')),
                ('start_send', models.CharField(help_text='Пример 20.08', verbose_name='Начало отправки')),
                ('end_send', models.CharField(help_text='Пример 20.08', verbose_name='Конец отправки')),
            ],
            options={
                'verbose_name': 'Квартал',
                'verbose_name_plural': 'Кварталы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sended', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('start_period', models.DateField(verbose_name='Начало')),
                ('end_period', models.DateField(verbose_name='Конец')),
                ('start_send', models.DateField(verbose_name='Начало отправки')),
                ('end_send', models.DateField(verbose_name='Конец отправки')),
                ('diaries', models.ManyToManyField(blank=True, to='diaries.diary', verbose_name='Дневники')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='local_hierarchy.diocese', verbose_name='Епархия')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.quarter', verbose_name='Квартал')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'unique_together': {('quarter', 'year', 'diocese')},
            },
        ),
    ]
