# Generated by Django 5.0.3 on 2025-10-15 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_hierarchy', '0002_alter_diocese_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('delited', 'Удален')], default='draft', verbose_name='Статус')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('place', models.CharField(blank=True, null=True, verbose_name='Место проведения')),
                ('member_count', models.CharField(blank=True, null=True, verbose_name='Количество участников')),
                ('type', models.CharField(blank=True, null=True, verbose_name='Тип')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_by_diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_diaries', to='local_hierarchy.diocese', verbose_name='Создано в епархии')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('held_in_diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helded_diocese', to='local_hierarchy.diocese', verbose_name='Проведено в епархии')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diaries.diary', verbose_name='Дневник')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/diary/', verbose_name='Изображение')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diaries.diary', verbose_name='Дневник')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
