# Generated by Django 5.0.3 on 2025-10-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Положительные черты'),
        ),
    ]
